using System.Collections.Generic;
using Newtonsoft.Json.Linq;
using UnityEngine;

/// <summary>
/// Converts exported POI JSON data into runtime POI models.
/// </summary>
/// <remarks>
/// The exported JSON is generated by THEODEN editor templates.
/// This translator extracts the relevant runtime information and maps it into
/// concrete <see cref="POIModel"/> subclasses.
///
/// This class does not load media assets. It only copies Addressables address strings
/// from the JSON into the runtime model. Media loading is handled separately by
/// <see cref="POIAssetResolver"/>.
/// </remarks>
public static class POIJsonTraslator
{
    /// <summary>
    /// Converts an exported POI JSON string into the correct runtime POI model.
    /// </summary>
    /// <param name="json">
    /// Exported POI JSON string.
    /// </param>
    /// <returns>
    /// A concrete <see cref="POIModel"/> instance, or null if the JSON cannot be converted.
    /// </returns>
    public static POIModel FromJson(string json)
    {
        if (string.IsNullOrWhiteSpace(json))
        {
            Debug.LogError("[POIJsonTranslator] JSON is empty.");
            return null;
        }

        JObject root = JObject.Parse(json);

        JToken template = GetTemplateNode(root);
        JToken challenge = template?["challenge"];

        string challengeType = challenge?["type"]?.ToString();

        if (string.IsNullOrWhiteSpace(challengeType))
        {
            Debug.LogError("[POIJsonTranslator] Challenge type missing.");
            return null;
        }

        switch (challengeType)
        {
            case "multipleChoiceType":
                return ConvertMultipleChoice(template);

            case "OpenAnswerType":
            case "openAnswerType":
                return ConvertOpenAnswer(template);

            default:
                Debug.LogError("[POIJsonTranslator] Unsupported challenge type: " + challengeType);
                return null;
        }
    }

    /// <summary>
    /// Converts a multiple-choice POI JSON object into a runtime model.
    /// </summary>
    private static MultipleChoicePOIModel ConvertMultipleChoice(JToken template)
    {
        JToken challenge = template?["challenge"];
        JToken pointOfInterest = template?["gameData"]?["pointOfInterest"];
        JToken poiReference = template?["poi"];

        if (!ValidateCommonNodes(challenge, pointOfInterest, poiReference))
            return null;

        MultipleChoicePOIModel model = CreateBaseModel<MultipleChoicePOIModel>(
            challenge,
            pointOfInterest,
            poiReference
        );

        model.correctAnswer = challenge["correctAnswer"]?.ToString() ?? "";
        model.answers = ReadMultipleChoiceAnswers(challenge);

        Debug.Log(
            "[POIJsonTranslator] Multiple-choice POI translated: " +
            model.poiName +
            " | Images: " +
            model.images.Count +
            " | Answers: " +
            model.answers.Count
        );

        return model;
    }

    /// <summary>
    /// Converts an open-answer POI JSON object into a runtime model.
    /// </summary>
    private static OpenAnswerPOIModel ConvertOpenAnswer(JToken template)
    {
        JToken challenge = template?["challenge"];
        JToken pointOfInterest = template?["gameData"]?["pointOfInterest"];
        JToken poiReference = template?["poi"];

        if (!ValidateCommonNodes(challenge, pointOfInterest, poiReference))
            return null;

        OpenAnswerPOIModel model = CreateBaseModel<OpenAnswerPOIModel>(
            challenge,
            pointOfInterest,
            poiReference
        );

        model.correctAnswers = ReadOpenAnswerCorrectAnswers(challenge);

        Debug.Log(
            "[POIJsonTranslator] Open-answer POI translated: " +
            model.poiName +
            " | Images: " +
            model.images.Count +
            " | Correct answers: " +
            model.correctAnswers.Count
        );

        return model;
    }

    /// <summary>
    /// Creates and fills the shared base POI fields.
    /// </summary>
    private static TModel CreateBaseModel<TModel>(
        JToken challenge,
        JToken pointOfInterest,
        JToken poiReference)
        where TModel : POIModel, new()
    {
        TModel model = new TModel
        {
            poiId = poiReference["poiId"]?.ToString() ?? "",
            poiName = poiReference["poiName"]?.ToString() ?? "",
            category = pointOfInterest["category"]?.ToString() ?? "",

            shortSummary = pointOfInterest["story"]?["shortIntroductorySummary"]?.ToString() ?? "",
            fullNarrative = pointOfInterest["story"]?["fullNarrative"]?.ToString() ?? "",

            initialDescription = challenge["initialDescription"]?.ToString() ?? "",
            question = challenge["question"]?.ToString() ?? "",
            points = ReadChallengePoints(challenge),
            hint = challenge["hint"]?.ToString() ?? "",

            poiBadgeAddress = challenge["poiBadge"]?.ToString() ?? "",

            images = ReadImageReferences(pointOfInterest),

            musicAddress = ReadMusicAddress(pointOfInterest),
            audioDescriptionAddress = ReadAudioDescriptionAddress(pointOfInterest),

            isChallengeCompleted = false
        };

        return model;
    }

    /// <summary>
    /// Gets the template node from the exported JSON.
    /// </summary>
    /// <remarks>
    /// Some older exports may wrap the template inside a "template" property.
    /// Newer exports may serialize the template directly at the root.
    /// This method supports both shapes.
    /// </remarks>
    private static JToken GetTemplateNode(JObject root)
    {
        return root["template"] ?? root;
    }

    /// <summary>
    /// Validates common JSON nodes required by all POI challenge types.
    /// </summary>
    private static bool ValidateCommonNodes(JToken challenge, JToken pointOfInterest, JToken poiReference)
    {
        if (challenge == null)
        {
            Debug.LogError("[POIJsonTranslator] Challenge node missing.");
            return false;
        }

        if (pointOfInterest == null)
        {
            Debug.LogError("[POIJsonTranslator] PointOfInterest node missing.");
            return false;
        }

        if (poiReference == null)
        {
            Debug.LogError("[POIJsonTranslator] Poi reference missing.");
            return false;
        }
        
        string poiId = poiReference["poiId"]?.ToString() ?? "";

        if (string.IsNullOrWhiteSpace(poiId))
        {
            Debug.LogError("[POIJsonTranslator] Poi id missing.");
            return false;
        }

        return true;
    }

    /// <summary>
    /// Reads image Addressables addresses from the POI media node.
    /// </summary>
    private static List<POIModel.ImageReference> ReadImageReferences(JToken poi)
    {
        List<POIModel.ImageReference> images = new List<POIModel.ImageReference>();

        JArray imageAddresses = poi["media"]?["images"] as JArray;

        if (imageAddresses == null)
            return images;

        foreach (JToken imageAddressToken in imageAddresses)
        {
            string address = imageAddressToken?.ToString();

            if (string.IsNullOrWhiteSpace(address))
                continue;

            images.Add(new POIModel.ImageReference
            {
                address = address
            });
        }

        return images;
    }

    /// <summary>
    /// Reads the music Addressables address from the POI media node.
    /// </summary>
    private static string ReadMusicAddress(JToken poi)
    {
        return
            poi["media"]?["audio"]?["music"]?.ToString() ??
            poi["media"]?["audio"]?["musicAddress"]?.ToString() ??
            poi["media"]?["audio"]?["musicGUID"]?.ToString() ??
            "";
    }

    /// <summary>
    /// Reads the audio description Addressables address from the POI media node.
    /// </summary>
    private static string ReadAudioDescriptionAddress(JToken poi)
    {
        return
            poi["media"]?["audio"]?["audioDescription"]?.ToString() ??
            poi["media"]?["audio"]?["audioDescriptionAddress"]?.ToString() ??
            poi["media"]?["audio"]?["audioDescriprion"]?.ToString() ??
            "";
    }

    /// <summary>
    /// Reads multiple-choice answer entries from the challenge node.
    /// </summary>
    private static List<MultipleChoicePOIModel.AnswerEntry> ReadMultipleChoiceAnswers(
        JToken challenge)
    {
        List<MultipleChoicePOIModel.AnswerEntry> answers =
            new List<MultipleChoicePOIModel.AnswerEntry>();

        JArray answerEntries = challenge["answers"]?["entries"] as JArray;

        if (answerEntries == null)
            return answers;

        foreach (JToken answer in answerEntries)
        {
            answers.Add(new MultipleChoicePOIModel.AnswerEntry
            {
                key = answer["key"]?.ToString() ?? "",
                value = answer["value"]?.ToString() ?? ""
            });
        }

        return answers;
    }

    /// <summary>
    /// Reads accepted correct answers from an open-answer challenge.
    /// </summary>
    private static List<string> ReadOpenAnswerCorrectAnswers(JToken challenge)
    {
        List<string> correctAnswers = new List<string>();

        JArray answers = challenge["answers"]?["correctAnswers"] as JArray;

        if (answers == null)
            return correctAnswers;

        foreach (JToken answer in answers)
        {
            string value = answer?.ToString();

            if (!string.IsNullOrWhiteSpace(value))
                correctAnswers.Add(value);
        }

        return correctAnswers;
    }
    
    /// <summary>
    /// Reads the configured challenge points and applies the default value
    /// when the field is missing, zero, negative, or malformed.
    /// </summary>
    private static int ReadChallengePoints(JToken challenge)
    {
        string serializedPoints = challenge?["points"]?.ToString();

        if (!int.TryParse(serializedPoints, out int configuredPoints))
            configuredPoints = 0;

        return TheodenScoringRules.ResolveChallengePoints(configuredPoints);
    }
}