using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using UnityEngine;
using UnityEngine.Serialization;

namespace Core.Models
{
    /// <summary>
    /// Runtime model for directions that guide the player toward the next Point of Interest.
    /// </summary>
    /// <remarks>
    /// This model is built from the exported directions JSON.
    ///
    /// Fields ending with "Address" are Addressables addresses generated by the editor export pipeline.
    /// Runtime-only loaded assets are marked with <see cref="JsonIgnore"/>.
    /// </remarks>
    [Serializable]
    public class DirectionsToNextPOIModel
    {
        /// <summary>
        /// Runtime representation of an image referenced by the directions data.
        /// </summary>
        [Serializable]
        public class ImageReference
        {
            /// <summary>
            /// Addressables address of the image sprite.
            /// </summary>
            public string address;

            /// <summary>
            /// Sprite loaded at runtime from the Addressables address.
            /// </summary>
            [JsonIgnore]
            public Sprite sprite;
        }

        /// <summary>
        /// Display name of the destination POI.
        /// </summary>
        [FormerlySerializedAs("levelName")] public string poiName;

        /// <summary>
        /// Id of the destination POI.
        /// </summary>
        public string poiId;

        /// <summary>
        /// Textual directions shown to the player.
        /// </summary>
        public string description;

        /// <summary>
        /// Direction images referenced by Addressables address.
        /// </summary>
        public List<ImageReference> images = new List<ImageReference>();

        /// <summary>
        /// Addressables address of the optional audio description.
        /// </summary>
        public string audioDescriptionAddress;

        /// <summary>
        /// Audio description loaded at runtime.
        /// </summary>
        [JsonIgnore]
        public AudioClip audioDescription;
    }
}