using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using UnityEngine;

/// <summary>
/// Base runtime model for a Point of Interest loaded from exported THEODEN JSON data.
/// </summary>
/// <remarks>
/// This model contains both serialized data loaded from JSON and runtime-only references
/// to assets loaded through Addressables.
///
/// Fields ending with "Address" are Addressables addresses generated by the editor export pipeline.
/// They should be used at runtime with TheodenRuntimeContentLoader.LoadAssetAsync.
/// 
/// Runtime-only loaded assets are marked with <see cref="JsonIgnore"/> so they are not expected
/// to exist inside the exported JSON.
/// </remarks>
[Serializable]
public abstract class POIModel
{
    /// <summary>
    /// Runtime representation of an image referenced by a POI.
    /// </summary>
    [Serializable]
    public class ImageReference
    {
        /// <summary>
        /// Addressables address of the image sprite.
        /// </summary>
        public string address;

        /// <summary>
        /// Sprite loaded at runtime from the Addressables address.
        /// </summary>
        [JsonIgnore]
        public Sprite sprite;
    }
    
    /// <summary>
    /// Unique identifier of the Point of Interest.
    /// Used to track progression and prevent points from being awarded more than once.
    /// </summary>
    public string poiId;

    /// <summary>
    /// Display name of the Point of Interest.
    /// </summary>
    public string poiName;

    /// <summary>
    /// Category of the Point of Interest.
    /// </summary>
    public string category;

    /// <summary>
    /// Images associated with the Point of Interest.
    /// </summary>
    public List<ImageReference> images = new List<ImageReference>();

    /// <summary>
    /// Initial challenge description shown before the question.
    /// </summary>
    public string initialDescription;

    /// <summary>
    /// Challenge question.
    /// </summary>
    public string question;
    
    /// <summary>
    /// Number of points awarded to the player when this POI challenge is completed.
    /// </summary>
    public int points;

    /// <summary>
    /// Addressables address of the POI background music.
    /// </summary>
    public string musicAddress;

    /// <summary>
    /// Background music loaded at runtime.
    /// </summary>
    [JsonIgnore]
    public AudioClip music;

    /// <summary>
    /// Addressables address of the POI audio description.
    /// </summary>
    public string audioDescriptionAddress;

    /// <summary>
    /// Audio description loaded at runtime.
    /// </summary>
    [JsonIgnore]
    public AudioClip audioDescription;

    /// <summary>
    /// Addressables address of the POI badge sprite.
    /// </summary>
    public string poiBadgeAddress;

    /// <summary>
    /// Badge sprite loaded at runtime.
    /// </summary>
    [JsonIgnore]
    public Sprite poiBadge;

    /// <summary>
    /// Hint shown when the player gives a wrong answer.
    /// </summary>
    public string hint;

    /// <summary>
    /// Short summary shown after the POI challenge is completed.
    /// </summary>
    public string shortSummary;

    /// <summary>
    /// Full narrative shown after the POI challenge is completed.
    /// </summary>
    public string fullNarrative;

    /// <summary>
    /// True if the challenge for this POI has been completed during the current runtime session.
    /// </summary>
    [JsonIgnore]
    public bool isChallengeCompleted;
}